services:
  # PostgreSQL ve Redis local kullanıldığı için kaldırıldı

  rabbitmq:
    image: rabbitmq:3-management
    container_name: phoneregistry-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      # Persistence ayarları
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_DISK_FREE_LIMIT: 1GB
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 0.8
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq-config:/etc/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # API'ler ve Worker Service local çalıştığı için Docker'dan kaldırıldı

volumes:
  rabbitmq_data:

networks:
  default:
    name: phone-registry-network
