version: '3.8'

services:
  # PostgreSQL zaten local'de çalışıyor (localhost:5432)
  # Eğer PostgreSQL'i de Docker'da çalıştırmak isterseniz aşağıdaki yorumu kaldırın:
  # postgres:
  #   image: postgres:15
  #   container_name: phoneregistry-postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 1876
  #     POSTGRES_DB: PhoneRegistryDb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - phoneregistry-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: phoneregistry-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - phoneregistry-network

  redis:
    image: redis:7-alpine
    container_name: phoneregistry-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - phoneregistry-network

networks:
  phoneregistry-network:
    driver: bridge

volumes:
  # postgres_data: # PostgreSQL local'de çalıştığı için gerek yok
  redis_data: